<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Treffynnon\\Navigator' => array($vendorDir . '/treffynnon/navigator/lib'),
    'Geocoder' => array($vendorDir . '/willdurand/geocoder/src'),
    'Composer\\Installers\\' => array($vendorDir . '/composer/installers/src'),
);
