<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitac57e949f6f5c83d10d0c3b9c0062e3b
{
    public static $prefixLengthsPsr4 = array (
        'G' =>
        array (
            'Geocoder\\' => 9,
        ),
        'C' =>
        array (
            'Composer\\Installers\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Geocoder\\' =>
        array (
            0 => __DIR__ . '/..' . '/willdurand/geocoder',
        ),
        'Composer\\Installers\\' =>
        array (
            0 => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers',
        ),
    );

    public static $prefixesPsr0 = array (
        'T' =>
        array (
            'Treffynnon\\Navigator' =>
            array (
                0 => __DIR__ . '/..' . '/treffynnon/navigator/lib',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitac57e949f6f5c83d10d0c3b9c0062e3b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitac57e949f6f5c83d10d0c3b9c0062e3b::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInitac57e949f6f5c83d10d0c3b9c0062e3b::$prefixesPsr0;
            $loader->classMap = ComposerStaticInitac57e949f6f5c83d10d0c3b9c0062e3b::$classMap;

        }, null, ClassLoader::class);
    }
}
