<?php return array(
    'root' => array(
        'name' => 'hypejunction/hypegeo',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => '717917c944813b85dedc0cc6f59c641861f1963c',
        'type' => 'elgg-plugin',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        'composer/installers' => array(
            'pretty_version' => 'v2.3.0',
            'version' => '2.3.0.0',
            'reference' => '12fb2dfe5e16183de69e784a7b84046c43d97e8e',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./installers',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'hypejunction/hypegeo' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '717917c944813b85dedc0cc6f59c641861f1963c',
            'type' => 'elgg-plugin',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'treffynnon/navigator' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => '60b9c19277f9453403e0a583c2abacd85404bf0f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../treffynnon/navigator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'willdurand/geocoder' => array(
            'pretty_version' => '5.0.0',
            'version' => '5.0.0.0',
            'reference' => 'a749e00819d2929bd0ec40fb79853956332970ba',
            'type' => 'library',
            'install_path' => __DIR__ . '/../willdurand/geocoder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
